# Appendix A – Status of Structures Assessed in the Field {-}

## Data-deficient Barriers {-}


```{r  echo = FALSE, results = 'asis'}
#| label: table-14
#| tbl-cap: "Table 14: Structures in Bulkley River watershed that have been assessed for fish passage for Pacific salmon and steelhead as of May 2026 but either require an additional in-depth fish-passage assessment to confirm the passability status or a habitat assessment to confirm upstream habitat values."  
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/bulk_data_deficient.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```


## Excluded Structures {-}

```{r  echo = FALSE, results = 'asis'}
#| label: table-15
#| tbl-cap: "Table 15: Structures in Bulkley River watershed that are excluded from further consideration in subsequent ranking and work planning because the structure is not present, is confirmed passable (e.g., bridge), or has no habitat upstream for Pacific salmon and steelhead." 
#| warning: false
#| echo: false
source("Rscripts/table_formatting.R")
library("flextable")

data <- read.csv("data/bulk_excluded.csv", check.names=FALSE)
ft <- flextable(data)
ft <- format_flextable(ft)
ft
```




